#!/bin/sh
#
# PROVIDE: pingwait
# REQUIRE: openvpn ipfw
#

. /etc/rc.subr

name="pingwait"
start_cmd="${name}_start"
stop_cmd=":"

pingwait_start()
{
  until ping -c1 www.google.com >/dev/null 2>&1; do :; done
}

load_rc_config $name
run_rc_command "$1"
